import type { Task, DashboardSummary, User, RecurringTemplate, ChecklistItem, ChecklistReport, ChecklistSummary } from "./types";

export const mockUsers: User[] = [
  { id: "1", name: "Admin Nusa", role: "owner" },
  { id: "2", name: "Leader KBU", role: "leader", outlet: "KBU" },
  { id: "3", name: "Leader Kisamen", role: "leader", outlet: "Kisamen" },
  { id: "4", name: "Staff Budi", role: "staff", outlet: "KBU" },
  { id: "5", name: "Staff Dewi", role: "staff", outlet: "Kisamen" },
];

export const mockTasks: Task[] = [
  {
    task_id: "TSK-001",
    token: "abc123xyz",
    created_at: "2024-01-15T08:00:00Z",
    created_by: "Admin Nusa",
    outlet: "KBU",
    area: "Dapur",
    category: "Cleaning",
    task_title: "Bersihkan Kitchen Hood",
    task_description:
      "Bersihkan kitchen hood dan filter secara menyeluruh. Pastikan tidak ada sisa minyak yang menempel.",
    priority: "High",
    pic_name: "Budi",
    pic_wa: "6281234567890",
    deadline: "2024-01-15T17:00:00Z",
    before_photo_url: "https://placehold.co/400x300/e2e8f0/64748b?text=Before",
    status: "OPEN",
    report_link: "/report/TSK-001?token=abc123xyz",
    wa_sent_at: "2024-01-15T08:05:00Z",
    is_late: false,
    last_updated: "2024-01-15T08:05:00Z",
  },
  {
    task_id: "TSK-002",
    token: "def456uvw",
    created_at: "2024-01-15T09:00:00Z",
    created_by: "Leader KBU",
    outlet: "KBU",
    area: "Bar",
    category: "Stock",
    task_title: "Cek Stock Sirup",
    task_description:
      "Periksa dan catat stock semua jenis sirup. Laporkan jika ada yang hampir habis.",
    priority: "Medium",
    pic_name: "Dewi",
    pic_wa: "6281234567891",
    deadline: "2024-01-15T12:00:00Z",
    status: "SUBMITTED",
    report_link: "/report/TSK-002?token=def456uvw",
    wa_sent_at: "2024-01-15T09:05:00Z",
    opened_at: "2024-01-15T09:30:00Z",
    submitted_at: "2024-01-15T11:45:00Z",
    after_photo_url: "https://placehold.co/400x300/dcfce7/166534?text=After",
    staff_note: "Stock sirup vanilla tinggal 2 botol",
    is_late: false,
    last_updated: "2024-01-15T11:45:00Z",
  },
  {
    task_id: "TSK-003",
    token: "ghi789rst",
    created_at: "2024-01-14T10:00:00Z",
    created_by: "Admin Nusa",
    outlet: "Kisamen",
    area: "Floor",
    category: "Cleaning",
    task_title: "Mop Lantai Area Makan",
    task_description: "Mop lantai area makan sampai bersih dan kering.",
    priority: "Low",
    pic_name: "Andi",
    pic_wa: "6281234567892",
    deadline: "2024-01-14T15:00:00Z",
    status: "DONE",
    report_link: "/report/TSK-003?token=ghi789rst",
    wa_sent_at: "2024-01-14T10:05:00Z",
    opened_at: "2024-01-14T10:15:00Z",
    submitted_at: "2024-01-14T14:30:00Z",
    after_photo_url: "https://placehold.co/400x300/dcfce7/166534?text=Done",
    staff_note: "Sudah bersih",
    leader_verification: "approved",
    verified_by: "Leader Kisamen",
    verified_at: "2024-01-14T14:45:00Z",
    is_late: false,
    duration_minutes: 255,
    last_updated: "2024-01-14T14:45:00Z",
  },
  {
    task_id: "TSK-004",
    token: "jkl012mno",
    created_at: "2024-01-15T07:00:00Z",
    created_by: "Leader Kisamen",
    outlet: "Samtaro Express",
    area: "Gudang",
    category: "Maintenance",
    task_title: "Perbaiki Rak Penyimpanan",
    task_description:
      "Rak penyimpanan di gudang goyang. Perbaiki atau ganti jika perlu.",
    priority: "Urgent",
    pic_name: "Rudi",
    pic_wa: "6281234567893",
    deadline: "2024-01-15T10:00:00Z",
    status: "LATE",
    report_link: "/report/TSK-004?token=jkl012mno",
    wa_sent_at: "2024-01-15T07:05:00Z",
    is_late: true,
    last_updated: "2024-01-15T07:05:00Z",
  },
  {
    task_id: "TSK-005",
    token: "pqr345stu",
    created_at: "2024-01-15T11:00:00Z",
    created_by: "Admin Nusa",
    outlet: "KBU",
    area: "Toilet",
    category: "Cleaning",
    task_title: "Bersihkan Toilet Customer",
    task_description:
      "Bersihkan toilet customer termasuk wastafel, kloset, dan lantai.",
    priority: "High",
    pic_name: "Siti",
    pic_wa: "6281234567894",
    deadline: "2024-01-15T14:00:00Z",
    before_photo_url: "https://placehold.co/400x300/e2e8f0/64748b?text=Before",
    status: "REVISI",
    report_link: "/report/TSK-005?token=pqr345stu",
    wa_sent_at: "2024-01-15T11:05:00Z",
    opened_at: "2024-01-15T11:30:00Z",
    submitted_at: "2024-01-15T13:00:00Z",
    after_photo_url: "https://placehold.co/400x300/fef3c7/92400e?text=Revisi",
    staff_note: "Sudah dibersihkan",
    leader_verification: "revision",
    verified_by: "Leader KBU",
    verified_at: "2024-01-15T13:15:00Z",
    is_late: false,
    last_updated: "2024-01-15T13:15:00Z",
  },
  {
    task_id: "TSK-006",
    token: "vwx678yza",
    created_at: "2024-01-15T06:00:00Z",
    created_by: "Leader KBU",
    outlet: "KBU",
    area: "Kasir",
    category: "General",
    task_title: "Cek Uang Kembalian",
    task_description:
      "Pastikan ketersediaan uang kembalian pecahan kecil mencukupi untuk operasional hari ini.",
    priority: "Medium",
    pic_name: "Nina",
    pic_wa: "6281234567895",
    deadline: "2024-01-15T08:00:00Z",
    status: "DONE",
    report_link: "/report/TSK-006?token=vwx678yza",
    wa_sent_at: "2024-01-15T06:05:00Z",
    opened_at: "2024-01-15T06:10:00Z",
    submitted_at: "2024-01-15T07:30:00Z",
    after_photo_url: "https://placehold.co/400x300/dcfce7/166534?text=Done",
    staff_note: "Sudah lengkap, tukar 500rb ke pecahan kecil",
    leader_verification: "approved",
    verified_by: "Leader KBU",
    verified_at: "2024-01-15T07:45:00Z",
    is_late: false,
    duration_minutes: 90,
    last_updated: "2024-01-15T07:45:00Z",
  },
];

export const mockDashboardSummary: DashboardSummary = {
  total: mockTasks.length,
  open: mockTasks.filter((t) => t.status === "OPEN").length,
  submitted: mockTasks.filter((t) => t.status === "SUBMITTED").length,
  done: mockTasks.filter((t) => t.status === "DONE").length,
  late: mockTasks.filter((t) => t.status === "LATE").length,
  revisi: mockTasks.filter((t) => t.status === "REVISI").length,
};

export const outlets = ["KBU", "Kisamen", "Samtaro Express"] as const;

export const areas = [
  "Dapur",
  "Bar",
  "Floor",
  "Gudang",
  "Toilet",
  "Outdoor",
  "Maintenance",
  "Kebon",
  "Kasir",
] as const;

export const categories = [
  "Cleaning",
  "Maintenance",
  "Stock",
  "Kitchen",
  "Bar",
  "Floor",
  "Waste",
  "General",
] as const;

export const priorities = ["Low", "Medium", "High", "Urgent"] as const;

export const staffList = [
  { name: "Budi", wa: "6281234567890", outlet: "KBU" },
  { name: "Dewi", wa: "6281234567891", outlet: "KBU" },
  { name: "Andi", wa: "6281234567892", outlet: "Kisamen" },
  { name: "Rudi", wa: "6281234567893", outlet: "Samtaro Express" },
  { name: "Siti", wa: "6281234567894", outlet: "KBU" },
  { name: "Nina", wa: "6281234567895", outlet: "KBU" },
];

// Recurring Templates Mock Data
export const mockRecurringTemplates: RecurringTemplate[] = [
  {
    template_id: "REC-001",
    template_name: "Checklist Opening Dapur",
    outlet: "KBU",
    area: "Dapur",
    category: "Cleaning",
    pic_name: "Budi",
    pic_wa: "6281234567890",
    task_title: "Checklist Opening Dapur",
    task_description: "Checklist pembukaan dapur setiap pagi",
    repeat_type: "daily",
    repeat_days: ["senin", "selasa", "rabu", "kamis", "jumat", "sabtu", "minggu"],
    repeat_time: "07:00",
    deadline_time: "09:00",
    requires_photo: true,
    active_status: true,
    template_version: 1,
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-01-10T08:00:00Z",
  },
  {
    template_id: "REC-002",
    template_name: "Cek Stock Mingguan",
    outlet: "KBU",
    area: "Gudang",
    category: "Stock",
    pic_name: "Dewi",
    pic_wa: "6281234567891",
    task_title: "Cek Stock Bahan Baku",
    task_description: "Cek dan catat stock bahan baku di gudang",
    repeat_type: "weekly",
    repeat_days: ["senin"],
    repeat_time: "10:00",
    deadline_time: "12:00",
    requires_photo: true,
    active_status: true,
    template_version: 1,
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-01-10T08:00:00Z",
  },
  {
    template_id: "REC-003",
    template_name: "Bersih-bersih Toilet",
    outlet: "Kisamen",
    area: "Toilet",
    category: "Cleaning",
    pic_name: "Andi",
    pic_wa: "6281234567892",
    task_title: "Bersihkan Toilet",
    task_description: "Bersihkan toilet customer dan staff",
    repeat_type: "custom",
    repeat_days: ["senin", "rabu", "jumat"],
    repeat_time: "14:00",
    deadline_time: "16:00",
    requires_photo: true,
    active_status: true,
    template_version: 1,
    created_at: "2024-01-11T08:00:00Z",
    updated_at: "2024-01-11T08:00:00Z",
  },
];

// Checklist Items Mock Data
export const mockChecklistItems: ChecklistItem[] = [
  // For REC-001 (Opening Dapur)
  {
    checklist_item_id: "CHK-001-01",
    template_id: "REC-001",
    item_order: 1,
    item_text: "Nyalakan kompor dan cek api",
    requires_photo: false,
    is_required: true,
    active_status: true,
  },
  {
    checklist_item_id: "CHK-001-02",
    template_id: "REC-001",
    item_order: 2,
    item_text: "Cek suhu kulkas (harus di bawah 5°C)",
    requires_photo: true,
    is_required: true,
    active_status: true,
  },
  {
    checklist_item_id: "CHK-001-03",
    template_id: "REC-001",
    item_order: 3,
    item_text: "Siapkan bahan mise en place",
    requires_photo: false,
    is_required: true,
    active_status: true,
  },
  {
    checklist_item_id: "CHK-001-04",
    template_id: "REC-001",
    item_order: 4,
    item_text: "Bersihkan meja prep",
    requires_photo: true,
    is_required: true,
    active_status: true,
  },
  {
    checklist_item_id: "CHK-001-05",
    template_id: "REC-001",
    item_order: 5,
    item_text: "Cek stock bumbu dasar",
    requires_photo: false,
    is_required: false,
    active_status: true,
  },
  // For REC-002 (Stock Mingguan)
  {
    checklist_item_id: "CHK-002-01",
    template_id: "REC-002",
    item_order: 1,
    item_text: "Hitung stock beras",
    requires_photo: true,
    is_required: true,
    active_status: true,
  },
  {
    checklist_item_id: "CHK-002-02",
    template_id: "REC-002",
    item_order: 2,
    item_text: "Hitung stock minyak goreng",
    requires_photo: true,
    is_required: true,
    active_status: true,
  },
  {
    checklist_item_id: "CHK-002-03",
    template_id: "REC-002",
    item_order: 3,
    item_text: "Cek expired date semua bahan",
    requires_photo: false,
    is_required: true,
    active_status: true,
  },
];

// Checklist Reports Mock Data
export const mockChecklistReports: ChecklistReport[] = [
  {
    report_id: "RCHK-001",
    task_id: "CHK-TSK-001",
    template_id: "REC-001",
    token: "chk123abc",
    pic_name: "Budi",
    pic_wa: "6281234567890",
    outlet: "KBU",
    area: "Dapur",
    report_date: "2024-01-15",
    deadline: "2024-01-15T09:00:00Z",
    checklist_title: "Checklist Opening Dapur",
    items: mockChecklistItems.filter(i => i.template_id === "REC-001"),
    status: "OPEN",
    checked_items: [],
    revision_count: 0,
    is_late: false,
  },
  {
    report_id: "RCHK-002",
    task_id: "CHK-TSK-002",
    template_id: "REC-001",
    token: "chk456def",
    pic_name: "Budi",
    pic_wa: "6281234567890",
    outlet: "KBU",
    area: "Dapur",
    report_date: "2024-01-14",
    deadline: "2024-01-14T09:00:00Z",
    checklist_title: "Checklist Opening Dapur",
    items: mockChecklistItems.filter(i => i.template_id === "REC-001"),
    submitted_at: "2024-01-14T08:45:00Z",
    status: "DONE",
    checked_items: [
      { checklist_item_id: "CHK-001-01", is_checked: true },
      { checklist_item_id: "CHK-001-02", is_checked: true, photo_url: "https://placehold.co/400x300/dcfce7/166534?text=Kulkas" },
      { checklist_item_id: "CHK-001-03", is_checked: true },
      { checklist_item_id: "CHK-001-04", is_checked: true, photo_url: "https://placehold.co/400x300/dcfce7/166534?text=Meja" },
      { checklist_item_id: "CHK-001-05", is_checked: false },
    ],
    after_photo_url: "https://placehold.co/400x300/dcfce7/166534?text=Done",
    staff_note: "Semua beres, stock bumbu masih cukup",
    verified_by: "Leader KBU",
    verified_at: "2024-01-14T09:00:00Z",
    revision_count: 0,
    is_late: false,
  },
  {
    report_id: "RCHK-003",
    task_id: "CHK-TSK-003",
    template_id: "REC-002",
    token: "chk789ghi",
    pic_name: "Dewi",
    pic_wa: "6281234567891",
    outlet: "KBU",
    area: "Gudang",
    report_date: "2024-01-15",
    deadline: "2024-01-15T12:00:00Z",
    checklist_title: "Cek Stock Bahan Baku",
    items: mockChecklistItems.filter(i => i.template_id === "REC-002"),
    submitted_at: "2024-01-15T11:30:00Z",
    status: "SUBMITTED",
    checked_items: [
      { checklist_item_id: "CHK-002-01", is_checked: true, photo_url: "https://placehold.co/400x300/dcfce7/166534?text=Beras" },
      { checklist_item_id: "CHK-002-02", is_checked: true, photo_url: "https://placehold.co/400x300/dcfce7/166534?text=Minyak" },
      { checklist_item_id: "CHK-002-03", is_checked: true },
    ],
    staff_note: "Stock beras tinggal 5kg, perlu order",
    revision_count: 0,
    is_late: false,
  },
];

export const mockChecklistSummary: ChecklistSummary = {
  total: mockChecklistReports.length,
  open: mockChecklistReports.filter((r) => r.status === "OPEN").length,
  submitted: mockChecklistReports.filter((r) => r.status === "SUBMITTED").length,
  done: mockChecklistReports.filter((r) => r.status === "DONE").length,
  late: mockChecklistReports.filter((r) => r.status === "LATE").length,
  revisi: mockChecklistReports.filter((r) => r.status === "REVISI").length,
};

export const daysOfWeek = [
  { value: "senin", label: "Senin" },
  { value: "selasa", label: "Selasa" },
  { value: "rabu", label: "Rabu" },
  { value: "kamis", label: "Kamis" },
  { value: "jumat", label: "Jumat" },
  { value: "sabtu", label: "Sabtu" },
  { value: "minggu", label: "Minggu" },
] as const;
