"use client";

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle } from "lucide-react";

/**
 * Compatibility route for WhatsApp links generated by Google Apps Script.
 * GAS sends links in the query style: /report?task_id=XXX&token=YYY
 * The real staff report route is path-based: /report/[taskId]?token=YYY
 * This page bridges the two by redirecting to the correct URL.
 */
function ReportRedirectContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [invalid, setInvalid] = useState(false);

  useEffect(() => {
    const taskId = searchParams.get("task_id") || searchParams.get("taskId");
    const token = searchParams.get("token") || "";

    if (taskId && token) {
      router.replace(`/report/${taskId}?token=${token}`);
    } else {
      setInvalid(true);
    }
  }, [router, searchParams]);

  if (invalid) {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center p-6">
        <div className="w-24 h-24 rounded-full bg-destructive/10 flex items-center justify-center">
          <AlertTriangle className="w-12 h-12 text-destructive" />
        </div>
        <h1 className="text-2xl font-bold text-foreground mt-6 text-center">
          Link Tidak Valid
        </h1>
        <p className="text-lg text-muted-foreground mt-3 text-center">
          Link tugas tidak valid atau token salah. Hubungi leader.
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex flex-col items-center justify-center p-6">
      <div className="animate-spin rounded-full h-16 w-16 border-4 border-primary border-t-transparent" />
      <p className="text-xl font-medium text-foreground mt-6">Membuka Tugas...</p>
    </div>
  );
}

export default function ReportRedirectPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-background flex flex-col items-center justify-center p-6">
          <div className="animate-spin rounded-full h-16 w-16 border-4 border-primary border-t-transparent" />
          <p className="text-xl font-medium text-foreground mt-6">Memuat...</p>
        </div>
      }
    >
      <ReportRedirectContent />
    </Suspense>
  );
}
